### ISSUE TITLE
Alias implementation

### ISSUE THREAD

**Issue by matthewlehner** [anthonator/dirigible#1]
Hi there,

Just writing to find out if you plan on implementing the alias portion of the API?
http://docs.urbanairship.com/connect/connect_audience.html#aliases

I don't mind jumping in and sending a pull request if necessary, but wondered if you had any progress on this.

Cheers

**Comment by anthonator** [comment]
What are you trying to do with aliases that we're currently not supporting? Looking through the API documentation I'm not seeing anything specific to aliases. If you're wanting to assign an alias take a look at the device registration endpoints.

https://github.com/anthonator/dirigible/blob/master/lib/dirigible/device_registration.rb

**Comment by matthewlehner** [comment]
Ah, sorry.. Missed this in my scan. This will work perfectly for me. Thanks!
