### ISSUE TITLE
DeviceInformation.get_device_token is returning 406 Not Acceptable - works in web browser 

### ISSUE THREAD

**Issue by johnnaegle** [anthonator/dirigible#10]
This code is returning a 406 / Not Acceptable

``` ruby
all_tokens = Dirigible::DeviceInformation.list_device_tokens
token = all_tokens[:device_tokens].first[:device_token]

puts "Requesting device token for #{token}"

Dirigible::DeviceInformation.get_device_token(token)
```

I expected this to work as it works if I try it in a browser with the same credentials.  However, I get this:

```
Dirigible::NotAcceptable: {:message=>"Not Acceptable"}
```

Thoughts?  I can't see why this would be different from Dirigible than a web browser or the credentials would be different than the ``list_device_tokens` request.

Thanks

**Comment by z5h** [comment]
This is a bug I verified with urban airship.
Their own words:

> Now, while testing, I have noticed that the message returned is a "Not
> Acceptable" message, which should not be returned in this case for a
> valid
> APID.
> 
> I have gone ahead and created an Engineering ticket to have our
> Engineering Team take care of this bug and fix it.

**Comment by johnnaegle** [comment]
Same issue with `Dirigible::DeviceInformation.get_apid`

**Comment by anthonator** [comment]
Closing since this seems to be a UA issue.
