### ISSUE TITLE
GET requests are given body

### ISSUE THREAD

**Issue by z5h** [anthonator/dirigible#4]
GET requests are having their options set as body. 
https://github.com/anthonator/dirigible/blob/master/lib/dirigible/request.rb#L29

This has no effect and causes errors because required parameters won't be sent. e.g.
Dirigible::DeviceInformation.device_token_feedback('2013-11-15')

> [...]  Bad Request [...] since [...] This field is required

This seems easily fixable with 

```
        if (method==:get)
          request.params.merge!(options)
        else
          request.body = options.to_json
        end
```

I can create a pull request if this makes sense.

**Comment by anthonator** [comment]
I think this makes sense. A PR would be appreciated!

**Comment by anthonator** [comment]
New version pushed.
