### ISSUE TITLE
Using dirigible gem to work with multiple UrbanAirship apps from a single Rails app

### ISSUE THREAD

**Issue by uson1x** [anthonator/dirigible#6]
Hi

I liked the approach you used to build dirigible, but in my case I need to connect to multiple Urban Airship apps from a single Rails app. So I just wanted to ask for your opinion first. Do you think there is a way to quickly adapt dirigible for this? And maybe you would suggest me where to start from?

**Comment by uson1x** [comment]
This is how I've done it in the end.
Instead of creating push notifications this way:

```
response = Dirigible::Push.create(params)
```

I used Dirigible::API directly:

```
api = Dirigible::API.new({app_key: "<APP_KEY>", master_secret: "<APP_MASTER_SECRET>"})
response = api.post('/push', params)
```

Seems to be working well, thought it might be breaking some encapsulation.

**Comment by z5h** [comment]
@uson1x the ruby way would probably be to provide a block to a 'with config' method so as not to affect the global config:

```
Dirigible::API.with_config({app_key: "<APP_KEY>", master_secret: "<APP_MASTER_SECRET>"}) do
  response = api.post('/push', params)
  ...
end
#global config has not been altered
```
