### ISSUE TITLE
Parsing Device Registration Response fails

### ISSUE THREAD

**Issue by johnnaegle** [anthonator/dirigible#7]
I attempted to register a device from my server to see if I can migrate from using APNS directly to using Urban airship.

I made this call:
    Dirigible::DeviceRegistration.register_device_token('1111111111111111111111111111111111111111111111111111111111111111', {})

This came back from Urban airship with Status 200, and a body of "OK" when then failed JSON parsing.

```
(rdb:1) pp response.body
"OK"
(rdb:1) pp response.status
200
```

**Comment by z5h** [comment]
Urban Airship is inconsistent with when the header says the body is JSON and when the body actually is JSON.
I have a fix where I always try to JSON parse the body, and fallback to returning the body.
I've made some other changes/fixes and haven't gotten around to making a sensible pull request out of them.
https://github.com/z5h/dirigible/commit/a61c31d3dff38b816645affeb54860cc2e43b50e#diff-56ebbf2d472fdcb775146149b27e192eR23

**Comment by anthonator** [comment]
This is one of the annoying parts of the UA API. I know that they were returning empty response bodies but may have switched to returning 'OK'.

I think @z5h's approach makes more sense than what I currently have in there. Thanks for putting in the leg work.

**Comment by anthonator** [comment]
I pushed a fix for this based on @z5h's commit. Could someone take a look and verify the fix?

https://github.com/anthonator/dirigible/commit/81fb102c068072a283535f8b7486e8c2e9de92d3

**Comment by anthonator** [comment]
https://github.com/anthonator/dirigible/commit/3400aa366675350bd122974615bb01995798754c

**Comment by johnnaegle** [comment]
That looks good to me.

**Comment by anthonator** [comment]
Thanks.
